### ISSUE TITLE
annotate_genes issue

### ISSUE THREAD

**Issue by arghya1611** [shafferm/DRAM#10]
Hi,
Is the given command for genome bin annotations tested on FAA files? i seem to be getting an odd error.

DRAM.py annotate_genes -i 'FAA-FINAL-BINS/*.faa' -o ../DRAM-ALL-BINS-annotation --threads 36 --verbose
2020-07-03 18:43:09.836872: Annotation started
0:00:00.649114: Retrieved database locations and descriptions
0:00:00.656408: Turning genes from prodigal to mmseqs2 db
0:00:03.980502: Getting hits from kofam
0:22:30.685739: Getting forward best hits from peptidase
0:22:41.705260: Getting reverse best hits from peptidase
0:22:45.382869: Getting descriptions of hits from peptidase
0:22:49.779608: Getting hits from pfam
0:23:05.773334: Getting hits from dbCAN
0:23:30.028470: Getting hits from VOGDB
0:36:11.046523: Merging ORF annotations
Traceback (most recent call last):
  File "/data/Food/analysis/R0220_NIHAM/DRAM/bin/DRAM.py", line 117, in <module>
    args.func(**args_dict)
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 1029, in annotate_called_genes
    create_annotated_fasta(input_faa, annotations, annotated_faa, name=fasta_name)
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 436, in create_annotated_fasta
    write_sequence(generate_annotated_fasta(input_fasta, annotations, verbosity, name),
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/registry.py", line 1166, in write
    return io_registry.write(obj, format, into, **kwargs)
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/registry.py", line 619, in write
    writer(obj, into, **kwargs)
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/registry.py", line 1082, in wrapped_writer
    writer_function(obj, fhs[-1], **kwargs)
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/format/fasta.py", line 774, in _generator_to_fasta
    for header, seq_str, qual_scores in formatted_records:
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/format/_base.py", line 147, in _format_fasta_like_records
    for idx, seq in enumerate(generator):
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 394, in generate_annotated_fasta
    for seq in read_sequence(input_fasta, format='fasta'):
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/registry.py", line 1160, in read
    return io_registry.read(file, format=format, into=into, verify=verify,
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/registry.py", line 506, in read
    return (x for x in itertools.chain([next(gen)], gen))
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/registry.py", line 528, in _read_gen
    with _resolve_file(file, **io_kwargs) as (file, _, _):
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/util.py", line 203, in _resolve_file
    file, source, is_binary_file = _resolve(file, **kwargs)
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/util.py", line 57, in _resolve
    newfile = source.get_reader()
  File "/data/Food/analysis/R0220_NIHAM/DRAM/lib/python3.8/site-packages/skbio/io/_iosources.py", line 94, in get_reader
    return io.open(self.file, mode='rb')
FileNotFoundError: [Errno 2] No such file or directory: 'FAA-FINAL-BINS/*.faa'

**Comment by shafferm** [comment]
Thanks for the error report. The issue here is the formatting of your path as well as DRAM not throwing an error correctly. To pass multiple paths to DRAM the formatting of the string should be `'FAA-FINAL-BINS/*.faa'`. So if you rerun your command with the `*` added it should work. That command would be:

```DRAM.py annotate_genes -i 'FAA-FINAL-BINS/*.faa' -o ../DRAM-ALL-BINS-annotation --threads 36 --verbose```

Also DRAM should have throw an error saying no bins were found. I have added in a check for this in the annotate_genes workflow. This will be included in a future release. Thanks for the catch!
