### ISSUE TITLE
subprocess.CalledProcessError: mmseqs

### ISSUE THREAD

**Issue by cflores10** [shafferm/DRAM#102]
Hello,

I am receiving a subprocess.CalledProcessError after running the following code: DRAM.py annotate -i '/scratch1/flores5/GF_fastq/02_ASSEMBLE/contigs/*.fa' -o annotation

33 fastas found
2021-07-06 00:54:28.962181: Annotation started
0:00:00.022096: Retrieved database locations and descriptions
0:00:00.022138: Annotating GF2_mjMb2B_input_S53_megahit.contigs
0:21:26.734696: Turning genes from prodigal to mmseqs2 db
Traceback (most recent call last):
  File "/home/flores5/anaconda3/envs/DRAM/bin/DRAM.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/flores5/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/home/flores5/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1005, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/home/flores5/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 923, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/home/flores5/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 824, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/home/flores5/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 723, in annotate_orfs
    make_mmseqs_db(gene_faa, query_db, create_index=True, threads=threads, verbose=verbose)
  File "/home/flores5/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 46, in make_mmseqs_db
    run_process(['mmseqs', 'createdb', fasta_loc, output_loc], verbose=verbose)
  File "/home/flores5/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/flores5/anaconda3/envs/DRAM/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createdb', 'annotation/working_dir/GF2_mjMb2B_input_S53_megahit.contigs/tmp/genes.faa', 'annotation/working_dir/GF2_mjMb2B_input_S53_megahit.contigs/tmp/gene.mmsdb']' died with <Signals.SIGILL: 4>.

Any suggestions on how I can fix this?

**Comment by shafferm** [comment]
Can you try running `annotation/working_dir/GF2_mjMb2B_input_S53_megahit.contigs/tmp/genes.faa` from the folder where you ran DRAM? It looks like maybe it can't find that file. Alternately how much RAM is available on this system? Processing the predicted genes file for mmseqs2 shouldn't take too much RAM but it could explain this issue.

**Comment by franztastic** [comment]
Hi, I have the same issue as commented above: 
Once I run annotation/working_dir/GF2_mjMb2B_input_S53_megahit.contigs/tmp/genes.faa
that's my output:
zsh: no such file or directory: annotation/working_dir/GF2_mjMb2B_input_S53_megahit.contigs/tmp/genes.faa

How could I fix this?

Thank you very much for your help!

**Comment by shafferm** [comment]
Hi @franztastic,
What is in the folder `annotation/working_dir/GF2_mjMb2B_input_S53_megahit.contigs/tmp/`? Were any errors or warning raised before this? Also what version of DRAM are you running (you can run `DRAM-setup.py version` to get this information).
Mike

**Comment by franztastic** [comment]
Hi @shafferm, 
thank you very much for answering
i have the same errors as @cflores10. 


DRAM.py annotate -i './VirSorter/virsorter-out/Predicted_viral_sequences/*.fasta' -o annotation 
6 fastas found
2021-09-02 19:41:36.916680: Annotation started
0:00:00.027491: Retrieved database locations and descriptions
0:00:00.027555: Annotating VIRSorter_cat-1
0:00:00.312119: Turning genes from prodigal to mmseqs2 db
0:00:02.330967: Getting hits from kofam
0:01:35.660939: Getting forward best hits from peptidase
Traceback (most recent call last):
  File "/data/vpf/Laura/anaconda3/envs/DRAM/bin/DRAM.py", line 168, in <module>
    args.func(**args_dict)
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1006, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 944, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 845, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 778, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_locs['peptidase'], tmp_dir,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 663, in do_blast_style_search
    forward_hits = get_best_hits(query_db, target_db, working_dir, 'gene', db_name, bit_score_threshold,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 65, in get_best_hits
    run_process(['mmseqs', 'search', query_db, target_db, query_target_db, tmp_dir, '--threads', str(threads)],
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 39, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'search', 'annotation/working_dir/VIRSorter_cat-1/tmp/gene.mmsdb', '/data/vpf/Laura/anaconda3/envs/DRAM_data/peptidases.20210825.mmsdb', 'annotation/working_dir/VIRSorter_cat-1/tmp/gene_peptidase.mmsdb', 'annotation/working_dir/VIRSorter_cat-1/tmp/tmp', '--threads', '10']' returned non-zero exit status 1.
---

Also I cannot find anything related to "annotation".

 {1} $ DRAM-setup.py version                                         (19:44:58)
1.2.4


That's my version! 

Thank you very much for your help! 
Laura

**Comment by rmFlynn** [comment]
So the problem is that this command `mmseqs search annotation/working_dir/VIRSorter_cat-1/tmp/gene.mmsdb /data/vpf/Laura/anaconda3/envs/DRAM_data/peptidases.20210825.mmsdb annotation/working_dir/VIRSorter_cat-1/tmp/gene_peptidase.mmsdb annotation/working_dir/VIRSorter_cat-1/tmp/tmp --threads 10` is failing for an unknown reason. Typical causes are that a past run left some output files or some input file does not exist. You can try and fined the cause by running the above command in your working directory. Or running DRAM.py with the `--verbose` flag. One of these may produce a more informative error.

**Comment by franztastic** [comment]
Hi, 
Is it possible that's because there's no "peptidases.20210825.mmsdb"? I have peptidases.20210830 instead... how could I get this other file?
Thanks, 
Laura

**Comment by franztastic** [comment]
I have uploaded the database config, so don't need an answer! Thank you! :)
