### ISSUE TITLE
Issue running DRAM-v.py on HPC environment

### ISSUE THREAD

**Issue by shaman-narayanasamy** [shafferm/DRAM#114]
Dear authors, 

I am attempting to run `DRAM-v.py` on my HPC environment which uses the `slurm` job scheduler. I am running it as part of the Viral sequence identification SOP with VirSorter2 V.3. Accordingly, I installed all the three programs (`virsorter`, `checkv` and `DRAM-v`) using conda under an environment which I called `vs2`. I intend to run this on approximately a hundred of metagenomic/metatranscriptomic samples, using `snakemake` as the workflow automation tool. I am also using the `--use-conda` option of `snakemake` to ensure that the pipeline is reproducible. 

I have done the following: 
1) Interactive mode test run using `DRAM-v.py` directly [SUCCESSUL]
2) Interactive mode with `snakemake` [FAILED]
3) Passive mode with `snakemake` (i.e. launched from access node) [FAILED]

Given that launching `DRAM-v.py` interactively worked for me, I proceeded to export the environment to a `.yml` file, which I provide to `snakemake` to run using the `--use-conda` option. However, launching using `snakemake` both within  the cluster interactive mode and passive mode fails, both seemingly from the same error. Please find the relevant logs in the Addendum. 

My apologies for such a long post. I am unable to identify the exact point of failure. Could you please help me out with this issue. Any guidance is much appreciated.

Best regards,
Shaman

# Addendum

## 1) Interactive mode test run using `DRAM-v.py` directly
```
conda activate vs2
cd <working dir>
$ DRAM-v.py annotate -i VS2/Virsorter2/pass_2/for-dramv/final-viral-combined-for-dramv.fa -v VS2/Virsorter2/pass_2/for-dramv/viral-affi-contigs-for-dramv.tab -o VS2/Virsorter2/dramv-annotate --skip_trnascan --threads 6 --min_contig_size 1000
--- stdout omitted ---
DRAM-v.py distill -i VS2/Virsorter2/dramv-annotate/annotations.tsv -o VS2/Virsorter2/dramv-distill
--- stdout omitted ---
```
Everything works fine here, hence I know that my conda installation of the viral sequence identification SOP is good. 

## 2) Interactive mode with `snakemake`
```
$ TS_DIR="/scratch
/users/snarayanasamy/test_data/Virsorter2/Assemblies" TS_SAMPLES="VS2" MGE_OUTDIR="/scratch/users/snarayanasamy/test_d
ata/Virsorter2/results1" snakemake -j 12 --use-conda -fps workflows/MgePrediction virsorter2_prediction_workflow.done
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Job stats:
job               count    min threads    max threads
--------------  -------  -------------  -------------
VS2_PREDICTION        1              1              1
run_dramv             1             12             12
total                 2              1             12

Select jobs to execute...

[Mon Sep  6 15:31:53 2021]
rule run_dramv:
    input: VS2/Virsorter2/pass_2/for-dramv/final-viral-combined-for-dramv.fa, VS2/Virsorter2/pass_2/for-dramv/viral-af
fi-contigs-for-dramv.tab
    output: VS2/Virsorter2/dramv-annotate/annotations.tsv
    log: logs/VS2/dramv.log
    jobid: 4
    benchmark: benchmarks/VS2/dramv.txt
    wildcards: ts_sample=VS2
    threads: 12
    resources: tmpdir=/tmp


        # Must delete the folder that snakemake creates. This is necessary for successful execution of this tool
        rm -rf VS2/Virsorter2/dramv-annotate VS2/Virsorter2/dramv-distill

        DRAM-v.py annotate -i VS2/Virsorter2/pass_2/for-dramv/final-viral-combined-for-dramv.fa -v VS2/Virsorter2/pass
_2/for-dramv/viral-affi-contigs-for-dramv.tab -o VS2/Virsorter2/dramv-annotate --skip_trnascan --threads 12 --min_cont
ig_size 1000
        
        DRAM-v.py distill -i VS2/Virsorter2/dramv-annotate/annotations.tsv -o VS2/Virsorter2/dramv-distill
        
Activating conda environment: /mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f
83e81938f1ff3e90a36c3d8db
2021-09-06 15:31:56.065661: Viral annotation started
Traceback (most recent call last):
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d
8db/bin/DRAM-v.py", line 143, in <module>
    args.func(**args_dict)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d
8db/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 440, in annotate_vgfs
    db_handler = DatabaseHandler(db_locs['description_db'])
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d
8db/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 17, in __init__
    raise ValueError('Database does not exist at path %s' % database_loc)
ValueError: Database does not exist at path None
Traceback (most recent call last):
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d
8db/bin/DRAM-v.py", line 143, in <module>
    args.func(**args_dict)
 File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d
8db/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 440, in annotate_vgfs
    db_handler = DatabaseHandler(db_locs['description_db'])
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d
8db/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 17, in __init__
    raise ValueError('Database does not exist at path %s' % database_loc)
ValueError: Database does not exist at path None
Traceback (most recent call last):
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d
8db/bin/DRAM-v.py", line 143, in <module>
    args.func(**args_dict)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/mag_annotator/summarize_vgfs.py", line 219, in summarize_vgfs
    annotations = pd.read_csv(input_file, sep='\t', index_col=0).fillna('')
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'VS2/Virsorter2/dramv-annotate/annotations.tsv'
[Mon Sep  6 15:31:58 2021]
Error in rule run_dramv:
    jobid: 4
    output: VS2/Virsorter2/dramv-annotate/annotations.tsv
    log: logs/VS2/dramv.log (check log file(s) for error message)
    conda-env: /mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results1/.snakemake/conda/140a54f83e81938f1ff3e90a36c3d8db
    shell:
        
        # Must delete the folder that snakemake creates. This is necessary for successful execution of this tool
        rm -rf VS2/Virsorter2/dramv-annotate VS2/Virsorter2/dramv-distill

        DRAM-v.py annotate -i VS2/Virsorter2/pass_2/for-dramv/final-viral-combined-for-dramv.fa -v VS2/Virsorter2/pass_2/for-dramv/viral-affi-contigs-for-dramv.tab -o VS2/Virsorter2/dramv-annotate --skip_trnascan --threads 12 --min_contig_size 1000
        
        DRAM-v.py distill -i VS2/Virsorter2/dramv-annotate/annotations.tsv -o VS2/Virsorter2/dramv-distill
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/irisgpfs/users/snarayanasamy/repositories/gitlab/LAO_multiomics_CRISPR_iMGEs/.snakemake/log/2021-09-06T153152.071210.snakemake.log
```

## 3) Passive mode with `snakemake` (i.e. launched from access node)
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Thu Sep  9 13:21:43 2021]
rule run_dramv:
    input: VS2/Virsorter2/pass_2/for-dramv/final-viral-combined-for-dramv.fa, VS2/Virsorter2/pass_2/for-dramv/viral-affi-contigs-for-dramv.tab
    output: VS2/Virsorter2/dramv-annotate/annotations.tsv
    log: logs/VS2/dramv.log
    jobid: 0
    benchmark: benchmarks/VS2/dramv.txt
    wildcards: ts_sample=VS2
    threads: 12
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp


        # Must delete the folder that snakemake creates. This is necessary for successful execution of this tool
        rm -rf VS2/Virsorter2/dramv-annotate VS2/Virsorter2/dramv-distill

        DRAM-v.py annotate -i VS2/Virsorter2/pass_2/for-dramv/final-viral-combined-for-dramv.fa -v VS2/Virsorter2/pass_2/for-dramv/viral-affi-contigs-for-dramv.tab -o VS2/Virsorter2/dramv-annotate --skip_trnascan --threads 12 --min_contig_size 1000
        
        DRAM-v.py distill -i VS2/Virsorter2/dramv-annotate/annotations.tsv -o VS2/Virsorter2/dramv-distill
        
Activating conda environment: /mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1
Traceback (most recent call last):
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/bin/DRAM-v.py", line 143, in <module>
    args.func(**args_dict)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 440, in annotate_vgfs
    db_handler = DatabaseHandler(db_locs['description_db'])
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 17, in __init__
    raise ValueError('Database does not exist at path %s' % database_loc)
ValueError: Database does not exist at path None
Traceback (most recent call last):
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/bin/DRAM-v.py", line 143, in <module>
    args.func(**args_dict)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/mag_annotator/summarize_vgfs.py", line 219, in summarize_vgfs
    annotations = pd.read_csv(input_file, sep='\t', index_col=0).fillna('')
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'VS2/Virsorter2/dramv-annotate/annotations.tsv'
[Thu Sep  9 13:21:55 2021]
Error in rule run_dramv:
    jobid: 0
    output: VS2/Virsorter2/dramv-annotate/annotations.tsv
    log: logs/VS2/dramv.log (check log file(s) for error message)
    conda-env: /mnt/lscratch/users/snarayanasamy/test_data/Virsorter2/results_passive1/.snakemake/conda/9bbcb37d2895a07ad07599af9fcac6c1
    shell:
        
        # Must delete the folder that snakemake creates. This is necessary for successful execution of this tool
        rm -rf VS2/Virsorter2/dramv-annotate VS2/Virsorter2/dramv-distill

        DRAM-v.py annotate -i VS2/Virsorter2/pass_2/for-dramv/final-viral-combined-for-dramv.fa -v VS2/Virsorter2/pass_2/for-dramv/viral-affi-contigs-for-dramv.tab -o VS2/Virsorter2/dramv-annotate --skip_trnascan --threads 12 --min_contig_size 1000
        
        DRAM-v.py distill -i VS2/Virsorter2/dramv-annotate/annotations.tsv -o VS2/Virsorter2/dramv-distill
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

## Environment YAML file
```
name: vs2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - virsorter=2
  - dram
  - checkv
```

**Comment by shaman-narayanasamy** [comment]
Hi,

I was looking through the issues and stumbled upon issue #81 , which spoke about the `DRAM-setup.py export_config` and `DRAM-setup.py import_config` commands. Exporting then importing the config file works like a charm!

My apologies for posting a redundant issue. I will proceed to close the issue.

Cheers,
Shaman
