### ISSUE TITLE
DRAM annotate fails at pfam step

### ISSUE THREAD

**Issue by slambrechts** [shafferm/DRAM#128]
Hi,

When running `DRAM.py annotate -i 'genomes/genomes/*.fasta' -o DRAM --threads 48`, it seems to fail at the pfam step (for each MAG), while getting hits for kofam and peptidases seems to work fine:

```
/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:120: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  hits[forward_hit] = [row.tId, rbh, row.seqIdentity, row.bitScore, row.eVal]
/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/database_handler.py:42: UserWarning: No descriptions were found for your id's. Does this PF02773.18 look like an id from pfam_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
1 fastas found
2021-11-29 17:14:30.225208: Annotation started
0:00:00.083813: Retrieved database locations and descriptions
0:00:00.083835: Annotating MAG015
0:00:47.475971: Turning genes from prodigal to mmseqs2 db
0:00:48.481523: Getting hits from kofam
0:25:22.741176: Getting forward best hits from peptidase
0:25:43.075736: Getting reverse best hits from peptidase
0:25:45.598773: Getting descriptions of hits from peptidase
0:25:45.653240: Getting hits from pfam
Traceback (most recent call last):
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/bin/DRAM.py", line 168, in <module>
    args.func(**args_dict)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1006, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 944, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 845, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 786, in annotate_orfs
    annotation_list.append(run_mmseqs_profile_search(query_db, db_locs['pfam'], tmp_dir, output_prefix='pfam',
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 204, in run_mmseqs_profile_search
    pfam_dict[gene] = '; '.join(['%s [%s]' % (pfam_descriptions[ascession], ascession)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 204, in <listcomp>
    pfam_dict[gene] = '; '.join(['%s [%s]' % (pfam_descriptions[ascession], ascession)
KeyError: 'PF09951.11'

```

I guess this has something to do with the warning message in the beginning of my screen output: 

```
 UserWarning: No descriptions were found for your id's. Does this PF02773.18 look like an id from pfam_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],

```

But what does that mean? Does it mean my pfam database is somehow corrupted or incomplete?

I have the following pfam files in  `/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files`:

```
-rw-rw-r-- 1 vsc42339 vsc42339 13521594214 Oct  1 15:58 Pfam-A.full.gz
-rw-rw-r-- 1 vsc42339 vsc42339      514890 Nov 24 22:59 Pfam-A.hmm.dat.gz
-rw-rw-r-- 1 vsc42339 vsc42339   107864190 Nov 24 22:50 pfam.mmspro
-rw-rw-r-- 1 vsc42339 vsc42339           4 Nov 24 22:50 pfam.mmspro.dbtype
-rw-rw-r-- 1 vsc42339 vsc42339      651878 Nov 24 22:50 pfam.mmspro_h
-rw-rw-r-- 1 vsc42339 vsc42339           4 Nov 24 22:50 pfam.mmspro_h.dbtype
-rw-rw-r-- 1 vsc42339 vsc42339      290121 Nov 24 22:50 pfam.mmspro_h.index
-rw-rw-r-- 1 vsc42339 vsc42339  9087864832 Nov 24 22:50 pfam.mmspro.idx
-rw-rw-r-- 1 vsc42339 vsc42339           4 Nov 24 22:50 pfam.mmspro.idx.dbtype
-rw-rw-r-- 1 vsc42339 vsc42339         334 Nov 24 22:50 pfam.mmspro.idx.index
-rw-rw-r-- 1 vsc42339 vsc42339      370910 Nov 24 22:50 pfam.mmspro.index

```

and `/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/DRAM.config` contains both a correct "pfam" and "pfam_hmm_dat" location:
```
"pfam": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/pfam.mmspro", "pfam_hmm_dat": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/Pfam-A.hmm.dat.gz"
```

Or is this because Pfam-A.full.gz was downloaded on Oct 1, while the other files are from Nov 24?

**Comment by slambrechts** [comment]
> Or is this because Pfam-A.full.gz was downloaded on Oct 1, while the other files are from Nov 24?

I can confirm this was the case, my mistake, solved
