### ISSUE TITLE
Error in DRAM-v.py distill

### ISSUE THREAD

**Issue by kodragonP** [shafferm/DRAM#13]
Hi there,
I use DRAM to annotate viral contigs, but
after I finished the annotate command, the following distill command report a error:
```
>>DRAM-v.py distill -i annotation/annotations.tsv -o distill
0:00:00.015109: Retrieved database locations and descriptions
Traceback (most recent call last):
  File "/home/wanglong/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4411, in get_value
    return libindex.get_value_at(s, key)
  File "pandas/_libs/index.pyx", line 44, in pandas._libs.index.get_value_at
  File "pandas/_libs/index.pyx", line 45, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 83, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wanglong/miniconda3/envs/DRAM/bin/DRAM-v.py", line 111, in <module>
    args.func(**args_dict)
  File "/home/wanglong/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/summarize_vgfs.py", line 225, in summarize_vgfs
    potential_amgs = filter_to_amgs(annotations.fillna(''), max_aux=max_auxiliary_score,
  File "/home/wanglong/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/summarize_vgfs.py", line 32, in filter_to_amgs
    vmap_aux_check = ('V' not in amg_flags) and ('M' in amg_flags) and (row['auxiliary_score'] <= max_aux) and \
  File "/home/wanglong/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/series.py", line 871, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/wanglong/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4419, in get_value
    raise e1
  File "/home/wanglong/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4405, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 90, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'auxiliary_score'
```

**Comment by shafferm** [comment]
Thanks for the error report! When you annotated your contigs did you use `DRAM.py annotate` or `DRAM-v.py annotate`? If you used `DRAM-v.py annotate` then what does the top line of your `annotations.tsv` file look like?

**Comment by kodragonP** [comment]
DRAM-v.py was used, and the top line of annotations.tsv is
        fasta   scaffold        gene_position   start_position  end_position    strandedness    rank    kegg_id kegg_hit        viral_id        viral_hit       viral_RBH       viral_identity  viral_bitScore  viral_eVal      peptidase_id    peptidase_family
        peptidase_hit   peptidase_RBH   peptidase_identity      peptidase_bitScore      peptidase_eVal  pfam_hits       cazy_hits
       vogdb_description       vogdb_categories        heme_regulatory_motif_count     is_transposon   amg_flags

**Comment by shafferm** [comment]
When you ran `DRAM-v.py` did you provide the VIRSorter affi contigs tab file? Or did you not provide anything for the `-v` flag? If you didn't provide that then you will not be able to distill with DRAM-v although you could distill with DRAM. DRAM needs the VIRSorter affi contigs file in order to determine the auxiliary score.

**Comment by gtrubl** [comment]
Hello,
I want to annotate my viruses not detected with VirSorter (DeepVirFinder) and I just tried and left out the -v parameter (DRAM-v.py annotate -i my_viral_contigs.fa -o annotation) as you said here. When it finished it came back 

"Traceback (most recent call last):
  File "/global/projectb/sandbox/pkmeco/gtrubl/.conda/envs/DRAM/bin/DRAM-v.py", line 111, in <module>
    args.func(**args_dict)
  File "/global/projectb/sandbox/pkmeco/gtrubl/.conda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_vgfs.py", line 350, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_locs_anno, db_handler, min_contig_size,
  File "/global/projectb/sandbox/pkmeco/gtrubl/.conda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 937, in annotate_fastas
    copy2(anno.gbk_loc, path.join(gbk_dir, '%s.gbk' % anno.name))
  File "/global/projectb/sandbox/pkmeco/gtrubl/.conda/envs/DRAM/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/global/projectb/sandbox/pkmeco/gtrubl/.conda/envs/DRAM/lib/python3.8/shutil.py", line 272, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/global/projectb/sandbox/pkmeco/gtrubl/.conda/envs/DRAM/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    raise err
  File "/global/projectb/sandbox/pkmeco/gtrubl/.conda/envs/DRAM/lib/python3.8/shutil.py", line 149, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
BlockingIOError: [Errno 11] Resource temporarily unavailable: 'annotate/working_dir/Blaze2_DVF_NODE_674_length_13679_cov_5.094597/Blaze2_DVF_NODE_674_length_13679_cov_5.094597.gbk' -> 'annotate/genbank/Blaze2_DVF_NODE_674_length_13679_cov_5.094597.gbk'"

While I did get an Annotation folder, I did not get the Tab separated file with all the annotations from Pfam, KEGG, UniProt, dbCAN, MEROPS, VOGDB:
"genbank  genes.faa  genes.fna  genes.gff  scaffolds.fna  trnas.tsv  vMAGs  working_dir"

I do not want any of the AMG scoring as with these viruses it is impossible, but I want the annotations/

Any suggestions?

Thanks,

Gary

**Comment by shafferm** [comment]
Hi Gary,

That is a weird one. It seems like the problem was in copying one of the results files after everything was complete. For a quick solution what you can do is merge the annotations for each virus. If you open python in your results folder you can run these commands.

```python
from glob import glob
import pandas as pd

dataframe_paths = glob('working_dir/*/annotations.tsv')
merged_annotations = pd.concat([pd.read_csv(i, sep='\t', index_col=0) for i in dataframe_paths])
merged_annotations.to_csv('annotations.tsv', sep='\t')
```

Could you also trying running it again and maybe doing your output in a different location? From the error is looks to me like either something got messed up with permissions and the copy failed because of that or maybe a disk was out of space and that blocked the copy?

**Comment by gtrubl** [comment]
Thank you.

I have never used glob commands before and tried to read up on it and could not find any documentation for "from glob" commands. I tried entering "from glob import glob" and it returns "command-not-found". Do I need to copy the above script and submit it together?

-Gary

**Comment by shafferm** [comment]
Hey Gary,

Sorry for not being clear. Those are python commands. So either you can copy those commands into a file and call it `merge_annotations.py` (or similar) and then call it as a script using `python merge_annotations.py`. Or you can open a python interpreter in your terminal and then copy those commands into the python interpreter.

Mike

**Comment by gtrubl** [comment]
Mike,

You are great and it worked. I appreciate the support. 

Thanks,

Gary
