### ISSUE TITLE
set up issues 

### ISSUE THREAD

**Issue by eawebb** [shafferm/DRAM#22]
HI mike,

DRAM looks really useful! but i cannot seem to get the Db installed. Conda install worked fine for DRAM, but i just got this error on centos HPC trying to install the DBs. I dont have access to KEGG, so i used this command. also the node that i was running it on has ~1Tb of RAM.

DRAM-setup.py prepare_databases --output_dir /scratch/eawebb/dram/DRAM_data --skip_uniref --threads 10

error:
Traceback (most recent call last):
File "/scratch/eawebb/miniconda/envs/DRAM/bin/DRAM-setup.py", line 144, in 
args.func(**args_dict)
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 446, in prepare_databases
output_dbs['pfam_db_loc'] = download_and_process_pfam(pfam_loc, temporary,
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 131, in download_and_process_pfam
download_file('ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz', pfam_full_zipped,
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 26, in download_file
run_process(['wget', '-O', output_file, url], verbose=verbose)
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 37, in run_process
return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', '/scratch/eawebb/dram/DRAM_data/database_files/Pfam-A.full.gz', 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz']' returned non-zero exit status 4.

Any ideas?

thanks!

eric

**Comment by eawebb** [comment]
hi ryan,

i went ahead downloaded Pfam-A.full.gz and uniref90.fasta.gz myself. Then i specified their locations. all seems to have gone well, but then i got this error. This node has >512 RAM.

thanks
e

File "/scratch/eawebb/miniconda/envs/DRAM/bin/DRAM-setup.py", line 144, in 
args.func(**args_dict)
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 446, in prepare_databases
output_dbs['pfam_db_loc'] = download_and_process_pfam(pfam_loc, temporary,
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 133, in download_and_process_pfam
pfam_profile = process_mmspro(pfam_full_zipped, output_dir, 'pfam', threads, verbose)
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 120, in process_mmspro
run_process(['mmseqs', 'msa2profile', mmseqs_msa, mmseqs_profile, '--match-mode', '1', '--threads', str(threads)],
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 37, in run_process
return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
File "/scratch/eawebb/miniconda/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'msa2profile', '/scratch/eawebb/dram/DRAM_data/database_files/pfam.mmsmsa', '/scratch/eawebb/dram/DRAM_data/database_files/pfam.mmspro', '--match-mode', '1', '--threads', '36']' died with <Signals.SIGABRT: 6>.

**Comment by Somebodyatthdoor** [comment]
Hi,

Just thought I'd add that I am getting a similar error during downloading of database files:

Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/DRAM/bin/DRAM-setup.py", line 144, in <module>
    args.func(**args_dict)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 443, in prepare_databases
    output_dbs['uniref_db_loc'] = download_and_process_uniref(uniref_loc, temporary, uniref_version=uniref_version,
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 110, in download_and_process_uniref
    download_file(uniref_url, uniref_fasta_zipped, verbose=verbose)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 26, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 37, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/laura_anaconda/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', 'DRAM_data/database_files/uniref90.fasta.gz', 'ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz']' returned non-zero exit status 8.
~

I also ran this on a cluster that should have had adequate RAM (~512 GB). 

Cheers,
Laura

**Comment by shafferm** [comment]
Hi @eawebb,

Sorry for the slow reply. I had missed your response. I would try running that command separately and see if it still fails. This might be an issue with mmseqs2. The command you can try running is `mmseqs pfam.mmsmsa pfam.mmspro --match-mode 1 --threads NUM_THREADS` where you replace `NUM_THREADS` with the number of threads you would like to run. You could also try restarting the database processing step and see if that works.

Mike

**Comment by shafferm** [comment]
Hi @Somebodyatthdoor,

It looks like DRAM was not able to run the command to download uniref90. Does the node you are running on have access to the internet? If it does then this could be cause by the internet connection on your node temporarily going down or UniRef being temporarily offline. You could download UniRef90 yourself and then give that the `DRAM-setup.py` by running `wget -O DRAM_data/database_files/uniref90.fasta.gz` or just try to run your same setup step again if you think this was caused by the internet connection having a temporary problem.

**Comment by Somebodyatthdoor** [comment]
Hi,

Thanks for your advice. The node can access the internet, not sure why it failed. I downloaded the datatbase as you suggested but when I try to run DRAM-setup.py I get an error because the database file already exists. Is there a way to make it ignore these errors, or will I have to go into the python files and change things?

Cheers,
Laura

**Comment by Somebodyatthdoor** [comment]
Sorry for the late reply, the problem now seems to have solved itself. I think there may have been an issue with the uniref website, but everything is now running smoothly.

Thanks for all of your help.
