### ISSUE TITLE
TypeError: 'datetime.datetime' object is not subscriptable

### ISSUE THREAD

**Issue by chandnisidhu** [shafferm/DRAM#25]
Hi,

I am getting this error while preparing databases. Please help.

DRAM-setup.py prepare_databases --output_dir DRAM_data --skip_uniref --threads 90
2020-08-25 17:11:46.381509: Database preparation started
0:28:53.183073: PFAM database processed
0:29:01.122199: dbCAN database processed
0:29:37.961948: RefSeq viral database processed
0:30:24.220746: MEROPS database processed
0:31:24.711691: VOGdb database processed
0:43:25.335451: KOfam database processed
0:43:29.674085: KOfam ko list processed
0:43:30.188671: PFAM hmm dat processed
0:43:30.756380: dbCAN fam activities processed
0:43:30.782741: VOGdb annotations processed
0:43:32.380609: DRAM databases and forms downloaded
0:43:32.395102: Files moved to final destination
0:43:32.395328: Setting database paths
0:43:32.395998: Database locations added to CONFIG
0:00:00.000002: Populating description database
Traceback (most recent call last):
  File "/home/csidhu/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 144, in <module>
    args.func(**args_dict)
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 524, in prepare_databases
    set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 353, in set_database_paths
    populate_description_db(db_dict, start_time)
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 373, in populate_description_db
    if db_dict['description_db'] is None and output_loc is not None:
TypeError: 'datetime.datetime' object is not subscriptable

**Comment by dnasko** [comment]
Was just about to post this. Getting the same error on my system (1TB RAM 4TB HDD storage) from the current release of DRAM (Git pulled on Monday) and running under the conda environment setup by the recommended `environment.yaml` file.

Fails after ~160 minutes of running because I'm not skipping UniRef. See below:

```bash
$ time DRAM-setup.py prepare_databases --output_dir DRAM_data
2020-08-25 19:44:50.366598: Database preparation started
1:45:19.238866: UniRef database processed
2:34:49.269863: PFAM database processed
2:34:54.574902: dbCAN database processed
2:35:08.518276: RefSeq viral database processed
2:36:00.569647: MEROPS database processed
2:37:25.222409: VOGdb database processed
2:43:05.485587: KOfam database processed
2:43:11.236348: KOfam ko list processed
2:43:13.361074: PFAM hmm dat processed
2:43:13.607013: dbCAN fam activities processed
2:43:14.239098: VOGdb annotations processed
2:43:15.029610: DRAM databases and forms downloaded
2:43:15.035304: Files moved to final destination
2:43:15.035391: Setting database paths
2:43:15.035687: Database locations added to CONFIG
0:00:00.000002: Populating description database
Traceback (most recent call last):
  File "/home/dan/software/anaconda3/envs/DRAM/bin/DRAM-setup.py", line 144, in <module>
    args.func(**args_dict)
  File "/home/dan/software/anaconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 524, in prepare_databases
    set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
  File "/home/dan/software/anaconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 353, in set_database_paths
    populate_description_db(db_dict, start_time)
  File "/home/dan/software/anaconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 373, in populate_description_db
    if db_dict['description_db'] is None and output_loc is not None:
TypeError: 'datetime.datetime' object is not subscriptable

real	163m18.628s
user	762m16.401s
sys	14m25.898s
```

**Comment by shafferm** [comment]
Could both of you run `DRAM-setup.py version` and let me know what prints out? I'm afraid this might be a bug introduced by the new version I put out last week. I'm working to reproduce this issue now. As a work around you could try installing the previous version of DRAM (`pip install DRAM-bio=1.0`).

**Comment by dnasko** [comment]
```bash
$ DRAM-setup.py version
1.1.0
```

**Comment by shafferm** [comment]
I think I have found the issue and am testing a fix now. If this fix works then I will push out a new version tomorrow and will update this thread.

Like I said in the previous post you can install the previous version and then install if you are in a hurry. Then you could upgrade to the newest version once you have finished setup.

**Comment by chandnisidhu** [comment]
> I think I have found the issue and am testing a fix now. If this fix works then I will push out a new version tomorrow and will update this thread.
> 
> Like I said in the previous post you can install the previous version. Then you could upgrade to the newest version once you have finished setup.

Thank you. Waiting for the new version :)

**Comment by shafferm** [comment]
@chandnisidhu @dnasko I have uploaded DRAM version 1.1.1 to pypi. You should now be able to install it with `pip install DRAM-bio`. Let me know if the error is fixed!

**Comment by chandnisidhu** [comment]
Hi,

I am getting the following error now:

` $ DRAM-setup.py prepare_databases --output_dir DRAM_data --skip_uniref --threads 80
2020-08-27 19:40:58.266640: Database preparation started
Traceback (most recent call last):
  File "/home/csidhu/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 458, in prepare_databases
    output_dbs['pfam_db_loc'] = download_and_process_pfam(pfam_loc, temporary,
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 131, in download_and_process_pfam
    download_file('ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz', pfam_full_zipped,
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 27, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', 'DRAM_data/database_files/Pfam-A.full.gz', 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz']' returned non-zero exit status 3.
`

**Comment by chandnisidhu** [comment]
Hi, 

I am getting this error now:

$ DRAM-setup.py prepare_databases --output_dir DRAM_data --skip_uniref --threads 80
2020-08-27 19:40:58.266640: Database preparation started
Traceback (most recent call last):
  File "/home/csidhu/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 458, in prepare_databases
    output_dbs['pfam_db_loc'] = download_and_process_pfam(pfam_loc, temporary,
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 131, in download_and_process_pfam
    download_file('ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz', pfam_full_zipped,
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 27, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/csidhu/miniconda3/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', 'DRAM_data/database_files/Pfam-A.full.gz', 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz']' returned non-zero exit status 3.

**Comment by shafferm** [comment]
@chandnisidhu can you try running that command outside of DRAM and see if it works (`wget -O DRAM_data/database_files/Pfam-A.full.gz ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz`)? You could also try running the same command again? The EBI FTP server may have been down when you tried to download.

**Comment by chandnisidhu** [comment]
> @chandnisidhu can you try running that command outside of DRAM and see if it works (`wget -O DRAM_data/database_files/Pfam-A.full.gz ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz`)? You could also try running the same command again? The EBI FTP server may have been down when you tried to download.

Hi, 

i guess it was my mistake. My disk was full. It is running now :)

**Comment by chandnisidhu** [comment]
@shafferm All databases have been downloaded successfully :)
