### ISSUE TITLE
setting up databases

### ISSUE THREAD

**Issue by nduan1** [shafferm/DRAM#28]
Hi Mike,
I got a problem when I ran "DRAM-setup.py prepare_databases --output_dir DRAM_data --skip_uniref" using 16 cores 256G RAM
Traceback (most recent call last):
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 458, in prepare_databases
    output_dbs['pfam_db_loc'] = download_and_process_pfam(pfam_loc, temporary,
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 131, in download_and_process_pfam
    download_file('ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz', pfam_full_zipped,
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 27, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', 'DRAM_data/database_files/Pfam-A.full.gz', 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz']' returned non-zero exit status 4.

I got this error when I tried to not skip uniref using 16 cores and 256 RAM
Traceback (most recent call last):
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 455, in prepare_databases
    output_dbs['uniref_db_loc'] = download_and_process_uniref(uniref_loc, temporary, uniref_version=uniref_version,
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 110, in download_and_process_uniref
    download_file(uniref_url, uniref_fasta_zipped, verbose=verbose)
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 27, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/lustre/haven/proj/UTK0124/ningd/conda/anaconda2/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', 'DRAM_data/database_files/uniref90.fasta.gz', 'ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz']' returned non-zero exit status 4.

Thanks! It would be great if I could have some instructions on this!

Ning

**Comment by mw55309** [comment]
Try running:

```sh
mkdir -p DRAM_data/database_files/
wget -O DRAM_data/database_files/Pfam-A.full.gz ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz
```

That's all the tool is trying to do, and it is returning an eror.

My guess would be your cluster nodes don't have download access - sometimes clusters are configured so the nodes cannot access the internet

**Comment by nduan1** [comment]
Thanks! It works
