### ISSUE TITLE
Issue with conda install?

### ISSUE THREAD

**Issue by morgvevans** [shafferm/DRAM#3]
Hi, really excited to use this tool but struggling to get it up and running.

It appears the conda install isn't complete - when I try to run any of the DRAM-setup.py scripts, it seems to be missing mag_annotator among other things, here's an example:

**(dram) -bash-4.2$ DRAM-setup.py -h**
Traceback (most recent call last):
  File "/users/PAS1331/osu7930/miniconda3/envs/dram/bin/DRAM-setup.py", line 4, in <module>
    __import__('pkg_resources').require('DRAM-bio==1.0.1')
  File "/users/PAS1331/osu7930/miniconda3/envs/dram/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/users/PAS1331/osu7930/miniconda3/envs/dram/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/users/PAS1331/osu7930/miniconda3/envs/dram/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/users/PAS1331/osu7930/miniconda3/envs/dram/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/users/PAS1331/osu7930/miniconda3/envs/dram/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/users/PAS1331/osu7930/miniconda3/envs/dram/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'DRAM-bio==1.0.1' distribution was not found and is required by the application

I have tried to combine both the manual and conda installs (to get around installing all the dependencies manually, which for several reasons I don't want to do), which doesn't result in the same errors as above, but when I tried to download all the databases I think the conflicting scripts/packages are causing issues. This isn't the full log output of the DRAM_setup.py prepare_databases command under these conditions but here's the last part where the error occurs:
2020-04-02 17:35:44.492395: Database preparation started
2:15:36.595338: UniRef database processed
downloading ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.full.gz
3:45:35.735833: PFAM database processed
3:45:46.530825: dbCAN database processed
downloading ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.1.protein.faa.gz
downloading ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.2.protein.faa.gz
3:45:53.733466: RefSeq viral database processed
3:46:25.947552: MEROPS database processed
Traceback (most recent call last):
  File "/users/PAS1331/osu7930/miniconda3/envs/dram/bin/DRAM-setup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/fs/project/PAS1331/DRAM/scripts/DRAM-setup.py", line 128, in <module>
    args.func(**args_dict)
  File "/fs/project/PAS1331/DRAM/mag_annotator/database_processing.py", line 446, in prepare_databases
    output_dbs['vogdb_db_loc'] = download_and_process_vogdb(vogdb_loc, temporary, vogdb_release=vogdb_version,
  File "/fs/project/PAS1331/DRAM/mag_annotator/database_processing.py", line 239, in download_and_process_vogdb
    merge_files(path.join(hmm_dir, 'VOG*.hmm'), vog_hmms)
  File "/fs/project/PAS1331/DRAM/mag_annotator/utils.py", line 72, in merge_files
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D'

Again I think this might be conflicting between conda and manual installs potentially?

If this is something I am overlooking on my end I'm sorry to bother you, but any input would be greatly appreciated! Thanks!

**Comment by shafferm** [comment]
Hi Morgan!

Sorry for being slow to get to this. We just pushed out a new version of DRAM and needed to finish that before getting back to set up related issues.

It looks to me like you work around to get DRAM installed and running worked. In your initial install did you use `pip install DRAM-bio` to install DRAM within your DRAM conda environment?

Your error once you get DRAM working is a new one to me as well. Can you send me the command you used to run `DRAM.py prepare_databases`?

Thanks,
Mike

**Comment by shafferm** [comment]
@morgvevans I have found the issue and am working on a fix now. I will let you know when I have published a fix.

**Comment by morgvevans** [comment]
OK! Do you need anything from me re: above or other? Thank you so much.

**Comment by shafferm** [comment]
@morgvevans forgot to let you know that a fix for this issue has been pushed to the master branch but is not yet available on pip. If you reinstall from github then your issue should be fixed!
