### ISSUE TITLE
issue during DRAM annotation

### ISSUE THREAD

**Issue by javadgh6** [shafferm/DRAM#52]
Dear Developer,

I ran the following command to annotate a set of MAGs 
DRAM.py annotate --threads 30  --min_contig_size 2000 -o dram_annotation   -i 'genome.bins/*.fa'
it fails at **Merging ORF annotations** step
and give the following  error
Traceback (most recent call last):
  File "/home/***/tools/anaconda2/envs/DRAM/bin/DRAM.py", line 145, in <module>
    args.func(**args_dict)
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 963, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1000, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 919, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 850, in annotate_fasta
    add_intervals_to_gff(trna_loc, renamed_gffs, len_dict, make_trnas_interval, 'Name')
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 626, in add_intervals_to_gff
    gff = list(read_sequence(gff_loc, format='gff3'))
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/skbio/io/registry.py", line 1160, in read
    return io_registry.read(file, format=format, into=into, verify=verify,
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/skbio/io/registry.py", line 506, in read
    return (x for x in itertools.chain([next(gen)], gen))
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/skbio/io/registry.py", line 531, in _read_gen
    yield from reader(file, **kwargs)
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/skbio/io/registry.py", line 1008, in wrapped_reader
    yield from reader_function(fhs[-1], **kwargs)
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/skbio/io/format/gff3.py", line 272, in _gff3_to_generator
    yield sid, _parse_record(data, length)
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/skbio/io/format/gff3.py", line 428, in _parse_record
    metadata.update(_parse_attr(columns[8]))
  File "/home/***/tools/anaconda2/envs/DRAM/lib/python3.9/site-packages/skbio/io/format/gff3.py", line 446, in _parse_attr
    k, v = attr.split('=')
ValueError: too many values to unpack (expected 2)

**Comment by mw55309** [comment]
Is it possible some of your contigs from different genomes have the same name?

**Comment by mw55309** [comment]
Awesome! Be good to close the issue :)
