### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by nduan1** [shafferm/DRAM#63]
Hi,

I got this error, could I have some suggestions? Thank you so much!

(DRAM) -bash-4.2$ DRAM-v.py annotate -i /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/virsorter12/M107/M107_virsort12_viralseqs.fa -v /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test1/done_psi_v1/output_psi_M107/Metric_files/VIRSorter_affi-contigs.tab -o /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/virsorter12/M107/test_annotation --threads 1
2021-02-13 11:00:50.933895: Viral annotation started
0:00:01.816081: Retrieved database locations and descriptions
0:00:01.816280: Annotating VIRSorter_k127_1224637-cat_1
0:00:02.219924: Turning genes from prodigal to mmseqs2 db
0:00:07.580697: Getting hits from kofam
Traceback (most recent call last):
  File "/lustre/haven/proj/UTK0124/conda2/envs/DRAM/bin/DRAM-v.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/lustre/haven/proj/UTK0124/DRAM/scripts/DRAM-v.py", line 139, in <module>
    args.func(**args_dict)
  File "/lustre/haven/proj/UTK0124/DRAM/mag_annotator/annotate_vgfs.py", line 361, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_locs_anno, db_handler, min_contig_size, prodigal_mode,
  File "/lustre/haven/proj/UTK0124/DRAM/mag_annotator/annotate_bins.py", line 922, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/lustre/haven/proj/UTK0124/DRAM/mag_annotator/annotate_bins.py", line 823, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/lustre/haven/proj/UTK0124/DRAM/mag_annotator/annotate_bins.py", line 734, in annotate_orfs
    annotation_list.append(run_hmmscan_kofam(gene_faa, db_locs['kofam'], tmp_dir,
  File "/lustre/haven/proj/UTK0124/DRAM/mag_annotator/annotate_bins.py", line 236, in run_hmmscan_kofam
    run_process(['hmmsearch', '--domtblout', output, '--cpu', str(threads), kofam_hmm, gene_faa], verbose=verbose)
  File "/lustre/haven/proj/UTK0124/DRAM/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/lustre/haven/proj/UTK0124/conda2/envs/DRAM/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hmmsearch', '--domtblout', '/lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/virsorter12/M107/test_annotation/working_dir/VIRSorter_k127_1224637-cat_1/tmp/kofam_profile.b6', '--cpu', '1', '/lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/kofam_profiles.hmm', '/lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/virsorter12/M107/test_annotation/working_dir/VIRSorter_k127_1224637-cat_1/tmp/genes.faa']' returned non-zero exit status 1.

(DRAM) -bash-4.2$ DRAM-setup.py print_config
KEGG db: None
KOfam db: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/kofam_profiles.hmm
KOfam KO list: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/kofam_ko_list.tsv
UniRef db: None
Pfam db: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/pfam.mmspro
Pfam hmm dat: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN db: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/dbCAN-HMMdb-V8.txt
dbCAN family activities: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/CAZyDB.07312019.fam-activities.txt
RefSeq Viral db: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/refseq_viral.20200926.mmsdb
MEROPS peptidase db: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/peptidases.20200926.mmsdb
VOGDB db: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/vog_latest_hmms.txt
VOG annotations: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/vog_annotations_latest.tsv.gz
Description db: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/description_db.sqlite
Genome summary form: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/genome_summary_form.20200926.tsv
Module step form: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/module_step_form.20200926.tsv
ETC module database: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/etc_mdoule_database.20200926.tsv
Function heatmap form: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/function_heatmap_form.20200926.tsv
AMG database: /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/amg_database.20200926.tsv

**Comment by nduan1** [comment]
(DRAM-new) -bash-4.2$ DRAM-setup.py version
1.1.1

**Comment by nduan1** [comment]
I ran this outside of DRAM
hmmsearch --domtblout /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/test_annotation/working_dir/VIRSorter_k127_1224637-cat_1/tmp/kofam_profile.b6 --cpu 1 /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/kofam_profiles.hmm /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/test_annotation/working_dir/VIRSorter_k127_1224637-cat_1/tmp/genes.faa

get this error info

Error: File existence/permissions problem in trying to open HMM file /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/kofam_profiles.hmm.
HMM file /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/DRAM_data/kofam_profiles.hmm not found (nor an .h3m binary

so I changed the file permission in DRAM_data by 
chmod u=rwx,g=r,o=r  filename

It works!

Ning
