### ISSUE TITLE
ValueError of DRAM-v

### ISSUE THREAD

**Issue by jiee1993** [shafferm/DRAM#70]
Hi,
  I encountered a ValueError when using DRAM-v to annotate viral predicted from Virsorter2. 

  DRAM-v is from version `DRAM 1.2.0`

  My command is :
  `DRAM-v.py annotate -i vs2-out/for-dramv/final-viral-combined-for-dramv.fa -v vs2-out/for-dramv/viral-affi-contigs-for-dramv.tab -o dram-v-annotation`

  The fully output message is : 

2021-03-23 12:43:35.019714: Viral annotation started  
0:02:01.824240: Retrieved database locations and descriptions
0:02:01.824368: Annotating VIRSorter_DK15SA4#k141_767189_length_4346_cov_15_0036-circular-cat_1__full-cat_1
0:02:01.919491: Turning genes from prodigal to mmseqs2 db
0:02:03.904472: Getting hits from kofam
0:03:01.681420: Getting forward best hits from viral
0:03:04.573272: Getting reverse best hits from viral
0:03:07.617804: Getting descriptions of hits from viral
0:03:07.639846: Getting forward best hits from peptidase
0:03:11.201309: Getting hits from pfam
0:03:17.686536: Getting hits from dbCAN
0:03:19.089490: Getting hits from VOGDB
0:03:57.002388: Merging ORF annotations
/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:557: UserWarning: No tRNAs were detected, no trnas.tsv file will be created.
  warnings.warn('No tRNAs were detected, no trnas.tsv file will be created.')
/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:578: UserWarning: No rRNAs were detected, no rrnas.tsv file will be created.
  warnings.warn('No rRNAs were detected, no rrnas.tsv file will be created.')
Traceback (most recent call last):
  File "/.conda/envs/DRAM-1.2.0/bin/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 403, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_locs_anno, db_handler, min_contig_size, prodigal_mode,
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 923, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 877, in annotate_fasta
    make_gbk_from_gff_and_fasta(renamed_gffs, renamed_scaffolds, annotated_faa, current_gbk)
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 504, in make_gbk_from_gff_and_fasta
    seq = read_sequence(io.StringIO(concat_gff), format='gff3', into=Sequence, seq_num=i)
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/skbio/io/registry.py", line 1160, in read
    return io_registry.read(file, format=format, into=into, verify=verify,
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/skbio/io/registry.py", line 513, in read
    return self._read_ret(file, format, into, verify, kwargs)
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/skbio/io/registry.py", line 520, in _read_ret
    return reader(file, **kwargs)
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/skbio/io/registry.py", line 998, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/skbio/io/format/gff3.py", line 294, in _gff3_to_sequence
    return _construct_seq(fh, Sequence, seq_num)
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/skbio/io/format/gff3.py", line 365, in _construct_seq
    seq = _get_nth_sequence(_fasta_to_generator(fh, constructor=constructor),
  File "/.conda/envs/DRAM-1.2.0/lib/python3.9/site-packages/skbio/io/format/_base.py", line 114, in _get_nth_sequence
    raise ValueError('Reached end of file before finding the %s sequence.'
ValueError: Reached end of file before finding the 1st sequence.

Do you have any suggestions to solve this problem？ Thanks~

**Comment by shafferm** [comment]
Hmm, I haven't seen this before. Could you post your `genes.gff` file from the `dram-v-annotation/working_dir/final-viral-combined-for-dramv` directory generated by DRAM.

**Comment by jiee1993** [comment]
Thanks for your kindly reply.
I think maybe the viral contig name is too long(i.e. VIRSorter_DK15SA4#k141_767189_length_4346_cov_15_0036-circular-cat_1__full-cat_1) caused this error. After I renamed the contig name(i.e. NODE.1) , the ValueError disappeared and dramv can continually annotate next contig.

**Comment by shafferm** [comment]
Great. I'll have to check if the `#` could be causing problems.
