### ISSUE TITLE
KeyError: 'YP_009822279.1' when using DRAM-v.py

### ISSUE THREAD

**Issue by ChenTianYi99** [shafferm/DRAM#86]
Hi,
i got an error when running DRAM-v.py. 

The error is:
2021-05-17 20:52:23.772081: Viral annotation started
0:01:22.357866: Retrieved database locations and descriptions
0:01:22.358104: Annotating VIRSorter_k141_1583097_length_44975_cov_86_9570-circular-cat_1
0:01:23.157359: Turning genes from prodigal to mmseqs2 db
0:01:25.360035: Getting hits from kofam
0:03:46.319434: Getting forward best hits from viral
0:03:48.336504: Getting reverse best hits from viral
0:03:50.008404: Getting descriptions of hits from viral
/lustre/home/liutang/01software/DRAM/mag_annotator/database_handler.py:42: UserWarning: No descriptions were found for your id's. Does this YP_009822279.1 look like an id from viral_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/lustre/home/liutang/.conda/envs/DRAM/bin/DRAM-v.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/lustre/home/liutang/01software/DRAM/scripts/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "/lustre/home/liutang/01software/DRAM/mag_annotator/annotate_vgfs.py", line 403, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_locs_anno, db_handler, min_contig_size, prodigal_mode,
  File "/lustre/home/liutang/01software/DRAM/mag_annotator/annotate_bins.py", line 923, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/lustre/home/liutang/01software/DRAM/mag_annotator/annotate_bins.py", line 824, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/lustre/home/liutang/01software/DRAM/mag_annotator/annotate_bins.py", line 751, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_locs['viral'], tmp_dir,
  File "/lustre/home/liutang/01software/DRAM/mag_annotator/annotate_bins.py", line 659, in do_blast_style_search
    hits = get_description(hits, header_dict)
  File "/lustre/home/liutang/01software/DRAM/mag_annotator/annotate_bins.py", line 161, in get_basic_description
    header = header_dict[hit]
KeyError: 'YP_009822279.1'

The command is:
DRAM-v.py annotate -i 30GC_WAP_vs1.fasta -o annotation -v VIRSorter_affi-contigs.tab

The database configurations are:
KEGG db: None
KOfam db: /lustre/home/liutang/01software/DRAM/DRAM_data/kofam_profiles.hmm
KOfam KO list: /lustre/home/liutang/01software/DRAM/DRAM_data/kofam_ko_list.tsv
UniRef db: /lustre/home/liutang/01software/DRAM/DRAM_data/uniref90.20210515.mmsdb
Pfam db: /lustre/home/liutang/01software/DRAM/DRAM_data/pfam.mmspro
Pfam hmm dat: /lustre/home/liutang/01software/DRAM/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN db: /lustre/home/liutang/01software/DRAM/DRAM_data/dbCAN-HMMdb-V9.txt
dbCAN family activities: /lustre/home/liutang/01software/DRAM/DRAM_data/CAZyDB.07302020.fam-activities.txt
RefSeq Viral db: /lustre/home/liutang/01software/DRAM/DRAM_data/refseq_viral.20210515.mmsdb
MEROPS peptidase db: /lustre/home/liutang/01software/DRAM/DRAM_data/peptidases.20210515.mmsdb
VOGDB db: /lustre/home/liutang/01software/DRAM/DRAM_data/vog_latest_hmms.txt
VOG annotations: /lustre/home/liutang/01software/DRAM/DRAM_data/vog_annotations_latest.tsv.gz
Description db: /lustre/home/liutang/01software/DRAM/DRAM_data/description_db.sqlite
Genome summary form: /lustre/home/liutang/01software/DRAM/DRAM_data/genome_summary_form.20210515.tsv
Module step form: /lustre/home/liutang/01software/DRAM/DRAM_data/module_step_form.20210515.tsv
ETC module database: /lustre/home/liutang/01software/DRAM/DRAM_data/etc_mdoule_database.20210515.tsv
Function heatmap form: /lustre/home/liutang/01software/DRAM/DRAM_data/function_heatmap_form.20210515.tsv
AMG database: /lustre/home/liutang/01software/DRAM/DRAM_data/amg_database.20210515.tsv

So how to deal with the problem? Looking forward to your reply.
Thanks.

**Comment by shafferm** [comment]
When you initially set up DRAM did it finish sucessfully? Can you try grep'ing for that database identifier? The command to do that is `grep -a YP_009822279.1 lustre/home/liutang/01software/DRAM/DRAM_data/refseq_viral.20200215.mmsdb_h `. When you run that do you get any results?

**Comment by franztastic** [comment]
Hello @shafferm ,
I'm here now with this same problem... I have just tried the command you suggest on your previous message and I have no result. 

DRAM.py annotate -i './VirSorter/virsorter-out/Predicted_viral_sequences/*.fasta' -o annotation                                                                                                                       (18:48:19)
6 fastas found
2021-09-22 18:48:27.600780: Annotation started
0:00:00.012670: Retrieved database locations and descriptions
0:00:00.012715: Annotating VIRSorter_cat-1
0:00:00.519381: Turning genes from prodigal to mmseqs2 db
0:00:03.150813: Getting hits from kofam
0:04:55.382149: Getting forward best hits from peptidase
0:04:56.569528: Getting hits from pfam
/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py:42: UserWarning: No descriptions were found for your id's. Does this PF04233.16 look like an id from pfam_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/data/vpf/Laura/anaconda3/envs/DRAM/bin/DRAM.py", line 168, in <module>
    args.func(**args_dict)
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1006, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 944, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 845, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 786, in annotate_orfs
    annotation_list.append(run_mmseqs_profile_search(query_db, db_locs['pfam'], tmp_dir, output_prefix='pfam',
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 204, in run_mmseqs_profile_search
    pfam_dict[gene] = '; '.join(['%s [%s]' % (pfam_descriptions[ascession], ascession)
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 204, in <listcomp>
    pfam_dict[gene] = '; '.join(['%s [%s]' % (pfam_descriptions[ascession], ascession)
KeyError: 'PF05396.13'


(DRAM) vpf@ltimbigd2: [~/Laura]
 {1} $ grep -a PF05396.13 ./anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb_h    

Thank you very much again and apologies for the disturbance...
Laura

**Comment by rmFlynn** [comment]
I think that in this case, the command you would want to run is:
`grep -a PF05396.13  ./anaconda3/envs/DRAM_data/pfam.mmspro_h`
That should give the header line, and if not run `DRAM-setup.py print_config` to double-check your db locations are where you expect them, and check any logs you have of DRAM set up to make sure it finished correctly.

**Comment by franztastic** [comment]
Hi rmFlynn, thank you very much for your help. 

I have solved what you said in the previous comment but now I am stucked again...

Trying now with DRAM-v.py

I have written all the db locations again and I have tried to solve when it gets an error using the --verbose flag, it gave me a lot of information. 
However, now I cannot see how can I solve this: 

That's my RefSeq viral location: 

RefSeq Viral db: /data/vpf/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb_h

when I run 

 DRAM-v.py annotate -i ./VirSorter/virsorter-out/Predicted_viral_sequences/*fa  -o annotation --verbose

I have this error:

Input database "/data/vpf/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb_h" has the wrong type (Generic)
Allowed input:
- Index
- Nucleotide
- Profile
- Aminoacid
...

So I change it to "refseq_viral.20210830.mmsdb.idx " as that's the other place I found "YP_009783939.1" when I did 

grep -a YP_009783939.1 ~/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb.idx                                                                              (16:56:37)
YP_009783939.1 capsid protein [Rhizobium phage RHEph01]

But now, that's what it says:

0:00:02.170732: Getting hits from kofam
0:01:00.060645: Getting forward best hits from viral
0:01:00.478685: Getting reverse best hits from viral
**Input /data/vpf/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb.idx_h does not exist**
Traceback (most recent call last):
  File "/data/vpf/Laura/anaconda3/envs/DRAM/bin/DRAM-v.py", line 143, in <module>
    args.func(**args_dict)
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 469, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_locs_anno, db_handler, min_contig_size, prodigal_mode,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 944, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 845, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 771, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_locs['viral'], tmp_dir,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 668, in do_blast_style_search
    reverse_hits = get_reciprocal_best_hits(query_db, target_db, working_dir, 'gene', db_name,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 98, in get_reciprocal_best_hits
    run_process(['mmseqs', 'createsubdb', query_target_db_filt_top_swapped, '%s_h' % target_db,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 39, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/data/vpf/Laura/anaconda3/envs/DRAM/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createsubdb', 'annotation/working_dir/VIRSorter_MV_AV_45_contig-100_44_length_8807_read_count_129263-cat_1/tmp/gene_viral.minbitscore60.tophit.swapped.mmsdb', '/data/vpf/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb.idx_h', 'annotation/working_dir/VIRSorter_MV_AV_45_contig-100_44_length_8807_read_count_129263-cat_1/tmp/viral.filt.mmsdb_h']' returned non-zero exit status 1.

And it's true, it does not exist. But I have any refseq_viral.20210830 with an index, nucleotide or profile ending also with "_h".

That's what I have and trying grep with all of "refseq_viral" these two ending one with _h and the other .idx are the only ones giving me results...

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/8795082/134776337-757e133f-f93d-451e-b4cd-756e6a051e11.png">

Sorry to bother you again..

Thank you very much,

Laura

**Comment by rmFlynn** [comment]
Looks like your location should be configured:  `RefSeq Viral db: /data/vpf/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb` with not `_h` or `.index` extension. You see,  `/data/vpf/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb` is the root that points to all these files. Let me know how that goes. Sorry for the long wait, somehow this just slipped through the cracks.

**Comment by franztastic** [comment]
Hi @rmFlynn , thank you very much for answering, that's the error I have now... thanks for helping!!! 

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/8795082/135886612-28107b3e-25fd-4e56-a9b2-0469bdb5e3bf.png">

**Comment by rmFlynn** [comment]
Hmm, did you use the setup process from the wiki or one of the alternatives like using the Zenodo data? I ask because usually we expect this problem to be with the setup of the databases being somehow cut off.   Try `grep -a YP_007001986.1  /data/vpf/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb_h` (check I copied that correctly) see if you get a hit.

**Comment by franztastic** [comment]
@rmFlynn Yes, I get a hit. I used the setup process from the wiki. It might be somehow cut when I did the downloading?

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/8795082/135890175-d96e263f-b741-4046-a7e1-a6d509740d79.png">

**Comment by rmFlynn** [comment]
Yes it is possible that setting up the databases again will solve the problem, but I would think that if it is in that file it can't give this error. I will consult with @shafferm. Can you run DRAM-setup.py print_config for me in the meantime, just to make sure everything is pointing to the correct destination, post the output here.

**Comment by franztastic** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/8795082/135893854-5ae35b2b-df7d-4547-a467-9e26d6517993.png">

@rmFlynn , That's the output for DRAM-setup.py print_config, THANK YOU VERY MUCH

**Comment by rmFlynn** [comment]
That looks good, while I am asking for things could you run `grep -a YP_007001986.1  /data/vpf/Laura/anaconda3/envs/DRAM_data/refseq_viral.20210830.mmsdb*` just to see if it is missing from somewhere else it should be.

**Comment by franztastic** [comment]
@rmFlynn , That's what I got ! 
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/8795082/135894882-b50aa3ba-7acd-4112-a9bb-7fe8af2f74ae.png">

**Comment by rmFlynn** [comment]
Ok the solution should be simple as running `DRAM-setup.py update_description_db` and then you should be able to run as normal. Thanks to @shafferm for point that out to me.

**Comment by franztastic** [comment]
thank you very much both!!! @rmFlynn @shafferm !!

**Comment by rmFlynn** [comment]
I am closing this issue as it seems to have been resolved.

**Comment by Sautumn-Lin** [comment]
> When you initially set up DRAM did it finish sucessfully? Can you try grep'ing for that database identifier? The command to do that is `grep -a YP_009822279.1 lustre/home/liutang/01software/DRAM/DRAM_data/refseq_viral.20200215.mmsdb_h `. When you run that do you get any results?


hello, I also met the same problem as below;
first time;
(DRAM) cat slurm-758026.out
/home/zlinbz/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this YP_003987171.1 look like an id from viral_description
  warnings.warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
2022-10-29 11:22:53.728280: Viral annotation started
0:00:00.043125: Retrieved database locations and descriptions
0:00:00.043157: Annotating final-viral-combined-for-dramv
0:00:14.944456: Turning genes from prodigal to mmseqs2 db
0:01:27.675080: Getting hits from kofam
0:34:15.834163: Getting forward best hits from viral
0:34:24.418456: Getting reverse best hits from viral
0:34:29.154187: Getting descriptions of hits from viral
Traceback (most recent call last):
  File "/home/zlinbz/miniconda3/envs/DRAM/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/zlinbz/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 475, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/zlinbz/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1013, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/zlinbz/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 921, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/home/zlinbz/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 814, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/home/zlinbz/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 684, in do_blast_style_search
    hits = formater(hits, header_dict)
  File "/home/zlinbz/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    header = header_dict[hit]
KeyError: 'YP_003987171.1'

grep -a YP_"*".1 /scratch/PI/boqianpy/App/DRAM_data/refseq_viral.20221029.mmsdb_h
After running this command, there were listed a lot of results.
and run again,
the error change as  follow,
KeyError: 'YP_003986888.1'(second time )
I don't know how to do that.


supplementary: (when run DRAM-setup.py print_config )
(DRAM)  DRAM-setup.py print_config
Processed search databases
KEGG db: None
KOfam db: /scratch/PI/boqianpy/App/DRAM_data/kofam_profiles.hmm
KOfam KO list: /scratch/PI/boqianpy/App/DRAM_data/kofam_ko_list.tsv
UniRef db: /scratch/PI/boqianpy/App/DRAM_data/uniref90.20221026.mmsdb
Pfam db: /scratch/PI/boqianpy/App/DRAM_data/pfam.mmspro
dbCAN db: /scratch/PI/boqianpy/App/DRAM_data/dbCAN-HMMdb-V10.txt
RefSeq Viral db: /scratch/PI/boqianpy/App/DRAM_data/refseq_viral.20221029.mmsdb
MEROPS peptidase db: /scratch/PI/boqianpy/App/DRAM_data/peptidases.20221029.mmsdb
VOGDB db: /scratch/PI/boqianpy/App/DRAM_data/vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: /scratch/PI/boqianpy/App/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN family activities: /scratch/PI/boqianpy/App/DRAM_data/CAZyDB.07292021.fam-activities.txt
VOG annotations: /scratch/PI/boqianpy/App/DRAM_data/vog_annotations_latest.tsv.gz

Description db: /scratch/PI/boqianpy/App/DRAM_data/description_db.sqlite

DRAM distillation sheets
Genome summary form: /scratch/PI/boqianpy/App/DRAM_data/genome_summary_form.20221029.tsv
Module step form: /scratch/PI/boqianpy/App/DRAM_data/module_step_form.20221029.tsv
ETC module database: /scratch/PI/boqianpy/App/DRAM_data/etc_mdoule_database.20221029.tsv
Function heatmap form: /scratch/PI/boqianpy/App/DRAM_data/function_heatmap_form.20221029.tsv
AMG database: /scratch/PI/boqianpy/App/DRAM_data/amg_database.20221029.tsv
