### ISSUE TITLE
DRAM-v.py exception when no significanct VOGDB hits

### ISSUE THREAD

**Issue by cerebis** [shafferm/DRAM#88]
I found that I receive an exception for some viral MAGs.

```python
Traceback (most recent call last):
  File "/shared/homes/120274/miniconda3/envs/DRAM/bin/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "/shared/homes/120274/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 409, in annotate_vgfs
    annotations = add_dramv_scores_and_flags(annotations, db_locs, virsorter_hits, input_fasta)
  File "/shared/homes/120274/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 343, in add_dramv_scores_and_flags
    annotations['amg_flags'] = pd.Series(get_metabolic_flags(annotations, metabolic_genes, amgs,
  File "/shared/homes/120274/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 245, in get_metabolic_flags
    if not pd.isna(row['vogdb_categories']):
  File "/shared/homes/120274/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/series.py", line 853, in __getitem__
    return self._get_value(key)
  File "/shared/homes/120274/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "/shared/homes/120274/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'vogdb_categories'
```

Going through the `mag_annotator` module, I believe I found the issue. When `annotate_bins.get_sig` is used to filter VOGDB hits for significance and the resulting list length is zero, you pass back an empty `pandas.Series` with the name `'vogdb_hits'` amd this practice is also employed when no VOGDB database was included.

It would seem that this column name is referenced no where else in your code. 

Further in `annotate_vgfs.get_metabolic_flags` you expect to always find `'vogdb_categories'` and test for an empty row field with `pd.isna(row['vogdb_categories'])`, only this fails when no hits were returned as no column named `vogdb_categories` was created.

I will shortly submit a pull request that rectifies this problem.

**Comment by shafferm** [comment]
Thanks for finding this! I thought I had found all of the bugs associated with returning no annotations from a database. I'll test this on my end today and I hope I can pull in your fix today or tomorrow.
