### ISSUE TITLE
DRAM. py annotate AssertionError

### ISSUE THREAD

**Issue by eholdridge** [shafferm/DRAM#93]
Hello,

There seems to be an issue with pandas when I try to run DRAM.py annotate on output files that were generated with VirSorter2 (development version with the --prep-for-dramv option). The error looks like:

```
Viral annotation started
Traceback (most recent call last):
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 568, in _list_to_arrays
    columns = _validate_or_indexify_columns(content, columns)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 692, in _validate_or_indexify_columns
2021-06-14 11:49:17.742492: Viral annotation started
Traceback (most recent call last):
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 568, in _list_to_arrays
2021-06-14 11:49:17.742491: Viral annotation started
Traceback (most recent call last):
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 568, in _list_to_arrays
    raise AssertionError(
AssertionError: 13 columns passed, passed data had 618 columns
```

I tried updating pandas but that didn't resolve the error. Any ideas about what might be causing this? Thank you in advance for any help you can provide!

Erica

**Comment by shafferm** [comment]
Hi Erica,

Is that the full traceback? Could you also reply with the full command you used to run DRAM-v? My suspicion is that you have FASTA headers which have extra `>` or `|` characters in them. You could try running `DRAM-v.py remove_bad_characters` on your FASTA and VIRSorter affi_contigs file before running DRAM to get around this issue.

Mike

**Comment by eholdridge** [comment]
Hi Mike,

Thanks for your response. I did run `DRAM-v.py remove_bad_characters` on both files before running DRAM on them. I was under the impression this removes `;` and `=` from the headers. So my headers now look like this:

`>k127_25179__0_partial-cat_4
CTACTGGAACATTTCTCCAGGATAGGCGCCCCAG`....

To run DRAM-v, I used:

`DRAM-v.py annotate -i virsorter2_output/for-dramv/final-viral-combined-for-dramv.fa -v virsorter2_output/for-dramv/viral-affi-contigs-for-dramv.tab -o annotation --threads 10 --min_contig_size 5000`

and the full traceback is:

`Viral annotation started
Traceback (most recent call last):
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 568, in _list_to_arrays
    columns = _validate_or_indexify_columns(content, columns)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 692, in _validate_or_indexify_columns
    columns = _validate_or_indexify_columns(content, columns)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 692, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 13 columns passed, passed data had 3654 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/bin/DRAM-v.py", line 140, in <module>
    raise AssertionError(
AssertionError: 13 columns passed, passed data had 1377 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/bin/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 378, in annotate_vgfs
    args.func(**args_dict)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 378, in annotate_vgfs
    virsorter_hits = get_virsorter_hits(virsorter_affi_contigs)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 104, in get_virsorter_hits
    virsorter_hits = get_virsorter_hits(virsorter_affi_contigs)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 104, in get_virsorter_hits
    virsorter_hits = pd.DataFrame(virsorter_rows, columns=VIRSORTER_COLUMN_NAMES).set_index('gene_name')
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/frame.py", line 570, in __init__
    virsorter_hits = pd.DataFrame(virsorter_rows, columns=VIRSORTER_COLUMN_NAMES).set_index('gene_name')
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/frame.py", line 570, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 528, in to_arrays
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 528, in to_arrays
    return _list_to_arrays(data, columns, coerce_float=coerce_float, dtype=dtype)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 571, in _list_to_arrays
    return _list_to_arrays(data, columns, coerce_float=coerce_float, dtype=dtype)
  File "/bsuhome/eholdridge/miniconda3/envs/DRAM/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 571, in _list_to_arrays
    raise ValueError(e) from e
ValueError: 13 columns passed, passed data had 1377 columns
    raise ValueError(e) from e
ValueError: 13 columns passed, passed data had 3654 columns`

Thanks again for your time and any help you can provide. I appreciate it. 

Erica

**Comment by shafferm** [comment]
Sorry for the slow reply! Looks like something is going wrong with parsing your virsorter affi contigs file. Could you share your affi contigs file? Either posting it here or email it to me? Then I can try to figure out what is going wrong.

**Comment by eholdridge** [comment]
No worries, and sorry for the delays on my end as well. I included a zip file with my VirSorter2 affi contig file here, both before (.tab) and after (.dram.tab) running `DRAM-v.py remove_bad_characters`. Thank you so much for your time!

[Holdridge_afficontig.zip](https://github.com/shafferm/DRAM/files/6777387/Holdridge_afficontig.zip)

**Comment by rmFlynn** [comment]
Looks like your affi tab is mising some new line caricters. Double check that your comand is 

`DRAM-v.py remove_bad_characters -v viral-affi-contigs-for-dramv.tab -o viral-affi-contigs-for-dramv.dram.tab`
and not
`DRAM-v.py remove_bad_characters -i viral-affi-contigs-for-dramv.tab -o viral-affi-contigs-for-dramv.dram.tab`

**Comment by eholdridge** [comment]
That was the problem - thank you, @rmFlynn and @shafferm !
