### ISSUE TITLE
ValueError: Reached end of file before finding the 1st sequence.

### ISSUE THREAD

**Issue by mujiezhang** [shafferm/DRAM#99]
Hello,
When I run  : DRAM-v.py annotate -i /lustre/home/acct-clsjhh/clsjhh/zmj/Hunt_Mu/database/DRAMv_result/5_error_fa.fa  -v /lustre/home/acct-clsjhh/clsjhh/zmj/Hunt_Mu/database/DRAMv_result/5_error_tab.tab -o 5_error_annotation --skip_trnascan --threads 35. And it run a small time then I got error following:
/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:578: UserWarning: No rRNAs were detected, no rrnas.tsv file will be created.
  warnings.warn('No rRNAs were detected, no rrnas.tsv file will be created.')
/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:578: UserWarning: No rRNAs were detected, no rrnas.tsv file will be created.
  warnings.warn('No rRNAs were detected, no rrnas.tsv file will be created.')
Traceback (most recent call last):
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/bin/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 403, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_locs_anno, db_handler, min_contig_size, prodigal_mode,
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 923, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 877, in annotate_fasta
    make_gbk_from_gff_and_fasta(renamed_gffs, renamed_scaffolds, annotated_faa, current_gbk)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 504, in make_gbk_from_gff_and_fasta
    seq = read_sequence(io.StringIO(concat_gff), format='gff3', into=Sequence, seq_num=i)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/skbio/io/registry.py", line 1160, in read
    return io_registry.read(file, format=format, into=into, verify=verify,
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/skbio/io/registry.py", line 513, in read
    return self._read_ret(file, format, into, verify, kwargs)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/skbio/io/registry.py", line 520, in _read_ret
    return reader(file, **kwargs)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/skbio/io/registry.py", line 998, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/skbio/io/format/gff3.py", line 294, in _gff3_to_sequence
    return _construct_seq(fh, Sequence, seq_num)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/skbio/io/format/gff3.py", line 365, in _construct_seq
    seq = _get_nth_sequence(_fasta_to_generator(fh, constructor=constructor),
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/DRAM_new/lib/python3.9/site-packages/skbio/io/format/_base.py", line 114, in _get_nth_sequence
    raise ValueError('Reached end of file before finding the %s sequence.'
ValueError: Reached end of file before finding the 1st sequence.
    So, I wonder what is the reason for this error.

**Comment by shafferm** [comment]
I have not seen this error before. How long are your viral sequences? Would you be okay sharing at least the first few lines from your input fasta file?

**Comment by mujiezhang** [comment]
Oh, really thanks for your reply! I have found the reason – bad character in sequence name…

发送自 Windows 10 版邮件应用

发件人: Michael Shaffer
发送时间: 2021年7月3日 6:30
收件人: shafferm/DRAM
抄送: mujiezhang; Author
主题: Re: [shafferm/DRAM] ValueError: Reached end of file before findingthe 1st sequence. (#99)

I have not seen this error before. How long are your viral sequences? Would you be okay sharing at least the first few lines from your input fasta file?
